//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub use super::favorite::Entity as Favorite;
pub use super::follower::Entity as Follower;
pub use super::post::Entity as Post;
pub use super::seaql_migrations::Entity as SeaqlMigrations;
pub use super::user::Entity as User;
